{% set name = "colorama" %}
{% set version = "0.4.0" %}
{% set build = 0 %}
{% set sha256 = "c9b54bebe91a6a803e0772c8561d53f2926bfeb17cd141fbabcb08424086595c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - colorama

about:
  home: https://github.com/tartley/colorama
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Cross-platform colored terminal text.'
  description: |
    colorama is a cross-platform colored terminal text.It makes
    ANSI escape character sequences (for producing colored terminal text
    and cursor positioning) work under MS Windows.
  doc_url: http://pypi.python.org/pypi/colorama
  doc_source_url: https://github.com/tartley/colorama/blob/master/README.rst
  dev_url: https://github.com/tartley/colorama

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
