{% set version = "0.3.9" %}

package:
  name: colorama
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/colorama/colorama-{{ version }}.tar.gz
  sha256: 48eb22f4f8461b1df5734a074b57042430fb06e1d61bd1e11b078c0fe6d7a1f1

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
  run:
    - python

test:
  imports:
    - colorama

about:
  home: https://github.com/tartley/colorama
  license: BSD 3-Clause
  summary: 'Cross-platform colored terminal text.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
