{% set name = "colorama" %}
{% set version = "0.3.9" %}
{% set build = 0 %}
{% set sha256 = "48eb22f4f8461b1df5734a074b57042430fb06e1d61bd1e11b078c0fe6d7a1f1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - colorama

about:
  home: https://github.com/tartley/colorama
  license: BSD 3-Clause
  summary: 'Cross-platform colored terminal text.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
