{% set version = "0.4.0" %}

package:
  name: colorama
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/colorama/colorama-{{ version }}.zip
  sha256: c9b54bebe91a6a803e0772c8561d53f2926bfeb17cd141fbabcb08424086595c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - colorama

about:
  home: https://github.com/tartley/colorama
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Cross-platform colored terminal text'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
