# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OIA5azYusbe0+R7BiYlgOM364S+T/dLNRsSxXn9t25fqmESo+xI3l2oyeZ3WpPmXTG9Izf2Rm26HT5UIImTxlBQZN0o/ADgzp370dFTtoJfSQMQqGL9INLIoS8eJzUNL67OT81Y8UJWk6PXmW2DED2HuNAjL+TaSz/+9tC5qozA0IUuwEGhL+OXzkpMsnFRj8kOsfjHZF7AVZPVGgg9TnDi//nPPJ3jqCu9jhR3tLumE1p521GYWVv1zGNbgIxU/c9V2RYIuoYlpUgAIIYXoJ3OaJrlKBedMmeFVYbSbpzkguoPPDgRbA9fcAdJFVD/5hopkQMO/FTtpxnn2GraWlMnuTUpGkKJDHfTKcZKtB/XmYDwWl8KNGosrAYGJtODs0keifOPjX7VbJmbt5LsEWB+7g1WA4WfZLa2I1nhxyWjmkgpHL/I8w2VeZgToWe4hmevHM0cSlygYClN2srA0piMznRazUQJiBpuw8uwIT160X8WdLv/UlZFN3aC4KtWHTtaIACM7g8Riqdhvhik75/j5bG3BBCXTmRe3sYGM8I6JhSL1j9wZj16bf7klM3NCupHuQos2fVnX1vEqZaPXzrp61DJPWcOVJEGz9i7HnjcN2rSHlhgSjd1A27YZCDrQArmwUXX9QeuzMKWg7Bisr4zhucRWhwGDGKrswCj9HcE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
