travis:
  secure:
    BINSTAR_TOKEN: 0VlsZXGyYQjqvrJYRzfBsqnZOxGhCVnVQhOW9YxLSG54iL0FFQAAAYj7g4CrnkEq6AHg+mK0iT2svdT/Zr5jaBlbL0Brya01C8MXVunwL5T0nzw8M0eap9qMBrC22yPliMBB3aheBPV8fnLJawzcHCvOQZ278tdgptkxrAn3IVe/3vUNiLl7vwW8H2zM/IuCb5BAMjTve2RN53S29yb9DBnlc6e/YMQ1zRF+EXKm2u2r1fJFG84sjAbEB7G9o27n5pykNDJyp6fRcoiu3T+m+4r6/1Lql6G0tNxrA3UnXTNu1JSEcj/THg5bT5H4TvETR9l0aRtGTsWLJOzJgGhIBHq+R6yUY0GFZ2Dse9H+5RfvExz0cPtYC8kAgd8YBxrrdz2l1BUKBR1poh3AtA+6zl/BabukEKQPkupL7IjVRZoRlPq+RarYw7SzP/Vqfa6BdSiHJnAu95kg1wQGlcZDMY7tPsJx2Ywxvb40VnwFett2LbYqBoYTVP6aZqPgj6KaqHbI7WCWWHa6yjE37rzJoqbmk3wYd8Jfswm5qihaz3HFrhEH5hqJNjqbX60+YNM4J44A+GQPawKRPqYSM4GxmwKAFj+nADzY2X6bjY6qImPmWP9VDCWrSehOkhEClvIVq2G8iIO4ZN809/yeJ3HR3UPCBlGy/hZx+hBUO6L3QNo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
